fix: Fix unnecessary use of list comprehension
Patol75/PyDRex pull request #12
Opened 2022-02-19 05:50 UTC by adigitoleo

2022-02-19 23:24 UTC, Patol75 requested changes

2022-02-19 23:24 UTC, Patol75 commented on src/pydrex/vtk_helpers.py
> +    return a[:, np.mod(list(range(a.shape[1])), n) != n - 1]
`np.arange(a.shape[1])`

2022-02-20 00:06 UTC, adigitoleo commented on src/pydrex/vtk_helpers.py
> +    return a[:, np.mod(list(range(a.shape[1])), n) != n - 1]
Thanks, fixed.

2022-02-20 02:56 UTC, Patol75 approved these changes

2022-02-20 02:56 UTC, merged