refactor: Overhaul core routines (again), add Mineral class
Patol75/PyDRex pull request #27
Opened 2022-03-09 05:45 UTC by adigitoleo

- Pathline stuff moved to its own file
- Introducing `Mineral`, to represent a mineral aggregate
- RK4 scheme is now a member of `Mineral` (`update_orientations`)
- Begginings of a test suite, still very work-in-progress

Reasons for change:
- The pathline way of doing things gets fiddly for a number of cases, e.g. zero velocity
- The pathline way is only useful for steady-state flow
- Refactoring onto a `Mineral` class makes it easier to run for single particles,
  e.g. a particle tracer
- Refactoring onto a `Mineral` class means that some nice metadata can be stored there
- The `core.derivatives` can now be jitted (maybe small speedups)

What is a `Mineral`? This idea is inspired by Fraters 2021.
A particle can store multiple minerals, which in turn store multiple grains.
So `Mineral` basically provides a container for grains, i.e. an aggregate.
In DRex, mineral phases don't interact and they rotate independently.

2022-03-09 05:45 UTC, adigitoleo commented
Also `Enum` -> `IntEnum` to appease numba.

2022-03-28 02:49 UTC, Patol75 requested changes
Looks great, well done!

2022-03-28 02:49 UTC, Patol75 commented on src/pydrex/core.py
> +    - `time_steps` (array) ̒— time steps for the iteration loop
Is there an extra character before the dash?

2022-03-28 02:49 UTC, Patol75 commented on src/pydrex/core.py
> +    Returns the finite strain ellipsoid after accumulated rotation.
rotationS?

2022-03-28 02:49 UTC, Patol75 commented on src/pydrex/core.py
> +    # Reference resolved shear stress (relative slip system "softness")
Delete?

2022-03-28 06:18 UTC, Patol75 approved these changes

2022-03-28 06:18 UTC, merged