Add aggregate test and CI file
Patol75/PyDRex pull request #30
Opened 2022-03-31 03:27 UTC by adigitoleo

- Replace ad-hoc RK4 with scipy version
- clean up pytest fixtures
- add test file for aggregate tests
- add CI file for test automation

All tests should pass in ~10s currently. The mineral aggregate test is a work-in-progress (it doesn't validate the results enough yet). I think there is still an issue with grain nucleation or something, because it looks like the grain size distribution is changed very drastically, very quicly. Some mockup plots of the olivine a-axis distribution also don't quite seem to match what they should right now.

2022-03-31 05:08 UTC, Patol75 requested changes

2022-03-31 05:08 UTC, Patol75 commented on .github/workflows/ci.yml
> +      - run: pytest
What about like this?

```
jobs:

  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install tests
        run: pip install -e .[test]

      - name: Run tests
        run: pytest
```

2022-03-31 09:00 UTC, adigitoleo commented on .github/workflows/ci.yml
> +      - run: pytest
b6f87ef

2022-04-02 09:49 UTC, Patol75 commented
`rebase` is always scary at first, no worries. Current changes look good to me, let me know if there are some further hurdles.

2022-04-07 06:38 UTC, adigitoleo commented
Pushing a squash rebase now, have removed the aggregate test for now, let's just get CI in because the aggregate test needs a little bit more work

2022-04-08 06:14 UTC, Patol75 commented on src/pydrex/minerals.py
> +        sol = RK45(
Small comment here, we are using RK45 at the moment, but we may end up changing to another solver depending on future benchmarks/models.

2022-04-08 06:16 UTC, Patol75 commented on src/pydrex/minerals.py
> +            # No rotation: carry over previous orientations.
Can you actually check if there is some mention of this somewhere in the DRex papers? Carrying over previous orientations sounds fair, but the Fortran reverts to the initial value, as we discussed.

2022-04-08 06:18 UTC, Patol75 approved these changes
Well done! I will merge, but please have a look at the two comments.

2022-04-08 06:18 UTC, merged