Docs
Patol75/PyDRex pull request #74
Opened 2023-02-28 07:06 UTC by adigitoleo

Add html documentation, also fix a few minor remaining naming convention issues.

Doesn't add automated deployment yet.

2023-02-28 10:37 UTC, adigitoleo commented
OK all good to go now. Deployment is to the gh-pages branch, so in the pages tab you just deploy from that branch:

![gh-pages-deploy](https://user-images.githubusercontent.com/34595875/221829471-90144f48-580f-48b1-84d7-42e35d48c3b2.png)

What it looks like on my fork: https://adigitoleo.github.io/PyDRex/

2023-03-01 03:44 UTC, Patol75 requested changes
Well, that is one wonderful piece of work! I could spot two typos, but perhaps there are more. You could quickly check that with something like Grammarly, for example, but far from necessary. Well done!

2023-03-01 03:44 UTC, Patol75 commented on src/pydrex/__init__.py
> +and an open-acess paper which discusses the model is [Fraters & Billen 2021](https://doi.org/10.1029/2021gc009846). [TODO: Add our paper]
"access" is missing a "c"

2023-03-01 03:44 UTC, Patol75 commented on src/pydrex/__init__.py
> +migratiton, by which process other grains of lower strain energy annex a portion
"migration"

2023-03-01 05:06 UTC, Patol75 approved these changes

2023-03-01 05:22 UTC, merged