More documentation fixes
Patol75/PyDRex pull request #81
Opened 2023-03-14 22:59 UTC by adigitoleo

- Make documentation of CRSS more precise
- Add missing enum docstrings
- Promote comments to docstrings in core tests

2023-03-15 23:17 UTC, Patol75 requested changes
Found one typo, the rest looks good!

2023-03-15 23:17 UTC, Patol75 commented on src/pydrex/minerals.py
> +    normalised to the stress required to initiate slip on the softes slip system
softest

2023-03-16 01:16 UTC, Patol75 approved these changes

2023-03-16 01:20 UTC, Patol75 commented
It seems like we have a test failure. Any merit in replacing some of these `assert` statements by [numpy.testing](https://numpy.org/doc/stable/reference/routines.testing.html) functions to get more information on failures? `np.testing.assert_allclose()` should be a good replacement for `assert np.isclose()`.

2023-03-16 02:16 UTC, adigitoleo commented
> test failure

I've edited the tolerance value and will submit that in the next test fixes. Apologies, I re-ran the job before reading your comment. The failure was once again due to one of the output diagnostics being slightly different and slightly past the tolerance.

There are two sources of randomness in the outputs:
- Random orientations in initial condition are not deterministic. Maybe I should seed the RNG for the tests.
- The diagnostics (M-index, angle) rely on re-sampled orientations, which once again uses an RNG. Maybe I should also seed that one for now, ultimately I would like for it to converge a bit better and am testing now with different number of grains, timesteps, etc.

> replacing some of these `assert` statements by [numpy.testing](https://numpy.org/doc/stable/reference/routines.testing.html) functions

I guess you mean using assert_allclose against the entire `misorient_angles`/`misorient_indices` arrays, instead of just assert statements against specific values? Currently that would make the test even more flaky, but it's probably a better approach once I seed the RNGs.

2023-03-16 02:17 UTC, merged